# Assignment/Task 4

### Pritam Poddar 
GO_STP_55

## 1) Import the numpy package under the name np and Print the numpy version and the configuration

In [ ]:
import numpy as NP

print("Numpy Version")
NP.__version__

print("Numpy Configuration")
NP.show_config()

Numpy Version
Numpy Configuration
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


## 2) Create a null vector of size 10

In [ ]:
Nv = NP.zeros(10)
Nv

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Creat One Vector of Size 5 
N =NP.ones(5)
N

array([1., 1., 1., 1., 1.])

## 3) Create Simple 1-D array and check type and check data types in array

In [ ]:
D =NP.arange(1,11)
D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Check the Type
type(D)

numpy.ndarray

In [ ]:
# Chcek the Data Type
D.dtype

dtype('int64')

## 4) How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
print('Number of dimension : ',D.ndim) 
print('Bytes per element : ',D.itemsize) 
print('Bytes of memory used : ',D.size*D.itemsize)


Number of dimension :  1
Bytes per element :  8
Bytes of memory used :  80


## 5) Create a null vector of size 10 but the fifth value which is 1

In [ ]:
N = NP.zeros(10)
N[4]=1
N

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 6) Create a vector with values ranging from 10 to 49

In [ ]:
X = NP.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 7) Reverse a vector (first element becomes last)

In [ ]:
# Normal way (with out using NP Function)
X = "Pritam"
print(X[::-1])

matirP


In [ ]:
# By using Numpy
Y = NP.arange(1,11)
print(Y[::-1])

[10  9  8  7  6  5  4  3  2  1]


## 8) Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
X = NP.arange(1,10).reshape(3,3)
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 9) Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
X =NP.array([1,2,0,0,4,0])
X.nonzero()

(array([0, 1, 4]),)

## 10) Create a 3x3 identity matrix


In [ ]:
X = NP.identity(3)
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 11) Create a 3x3x3 array with random values

In [ ]:
X = NP.random.random((3,3,3))
X

array([[[0.5739887 , 0.04078397, 0.09557361],
        [0.53174248, 0.69985895, 0.95504533],
        [0.0190968 , 0.34494062, 0.62873778]],

       [[0.77905201, 0.18594432, 0.09555533],
        [0.01419706, 0.94124113, 0.31261647],
        [0.01678954, 0.38414999, 0.98156459]],

       [[0.79539817, 0.12879132, 0.29127797],
        [0.97064608, 0.04863441, 0.34643437],
        [0.0490158 , 0.63982751, 0.43131619]]])

## 12) Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
import numpy as NP  
X = NP.random.random((10,10))
X

# Max Value
print("Max - ",X.max())
# Or
print("Max - ",NP.max(X))

print("----------------")

# Min Value
print("Min - ",X.min())
# Or
print("Min - ",NP.min(X))

Max -  0.9953427301112101
Max -  0.9953427301112101
----------------
Min -  0.0004897090024694739
Min -  0.0004897090024694739


# 13) Create a random vector of size 30 and find the mean value

In [ ]:
X1 = NP.random.random(30)
print(X1)
print("Size - ",NP.size(X1))
print("Shape - ",NP.shape(X1)) # 1D Array
print("Mean - ",NP.mean(X1))

[0.74575765 0.44844631 0.12736833 0.42261169 0.66103347 0.49435866
 0.20102369 0.71964269 0.87371833 0.6080915  0.29187254 0.9359361
 0.81042746 0.91772957 0.20448148 0.21214208 0.91025747 0.96979213
 0.29497095 0.67782561 0.70288821 0.92392554 0.1268867  0.61699056
 0.38138298 0.43050557 0.86283442 0.23571876 0.96860865 0.23401832]
Size -  30
Shape -  (30,)
Mean -  0.5670415811234103


# 14) Create a 2d array with 1 on the border and 0 inside

In [ ]:
X2 = NP.ones((5,5))
print("Original Array - ")
print(X2)

print("Creating array with 1 on the border and 0 inside")
X2[1:4,1:-1] = 0
print(X2)
print("Size - ",NP.size(X2))
print("Shape - ",NP.shape(X2))

Original Array - 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Creating array with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Size -  25
Shape -  (5, 5)


# 15) How to add a border (filled with 0's) around an existing array? 

In [ ]:
print("Existing Array - ")
print(X2)

print("Fill with 0 around in Existing Array - ")
X2[0:5,0:5] = 0
X2[1:4,1:4] = 1
print(X2)

Existing Array - 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Fill with 0 around in Existing Array - 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 16) How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
X = NP.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print("Original - ")
print(X)

print(X[1,-2])
print(X[0,1:6:2])
X[1,-2] = 20

print("After Changig  - ")
print(X)

Original - 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[2 4 6]
After Changig  - 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# 17) How to Convert a 1D array to a 2D array with 2 rows

In [ ]:
# Using Array
B = NP.array([1,2,3,4,5,6])
print(B)
print(NP.shape(B))
print(NP.size(B))

# Reshape
print(B.reshape(2,3))

[1 2 3 4 5 6]
(6,)
6
[[1 2 3]
 [4 5 6]]


In [ ]:
# Using Arange
B = NP.arange(1,7)
print(B)
print(NP.shape(B))
print(NP.size(B))

# Reshape
print(B.reshape(2,3))

[1 2 3 4 5 6]
(6,)
6
[[1 2 3]
 [4 5 6]]


# 18) Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
### Input:
####a = np.array([1,2,3])
### Desired Output:

#### array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [ ]:
A = NP.array([1,2,3])
print(A)

B = NP.append(NP.repeat(A,3),NP.tile(A,3))
print(B)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# 19) Write a program to show how Numpy taking less memory compared to Python List?

In [ ]:
L = range(1000)

import sys
print("LIST")
A=10
print("Memory per element : ",sys.getsizeof(A))   
print("Memory taken by list : ",sys.getsizeof(A)*len(L))

print("NUMPY ARRAY")
A1 = NP.arange(1000)
print("Memory per element : ",A1.size)
print("Memory taken by Numpy array : ",A1.size*A1.itemsize)

LIST
Memory per element :  28
Memory taken by list :  28000
NUMPY ARRAY
Memory per element :  1000
Memory taken by Numpy array :  8000


# 20) Write a program to show how Numpy taking less time compared to Python List?

In [ ]:

import numpy as np
import time
import sys

size = 1000000
l1 = range(size)
l2 = range(size)
n1 = np.arange(size)
n2 = np.arange(size)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Time taken by Python List : ",(time.time()-start)*1000)

start = time.time()
result1 = n1+n2
print("Time taken by NumPy Array : ",(time.time()-start)*1000)


Time taken by Python List :  144.6704864501953
Time taken by NumPy Array :  3.1888484954833984
